
(in-package :clml.test)

(define-test test-sample-som
  #+ lispworks
  (assert-prints
     (concatenate 'string
       (format nil "in-data-file [~s]~%" (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/som/animal.dat"))
       (format nil "s-topol[hexa] s-neigh[gaussian] xdim[24] ydim[16] nrand[123]~%")
       (format nil "num-label[10]~%")
       (format nil "step 1 : initialization ~%")
       (format nil "step 2 : learning ~%")
       (format nil "step 3 : calibration ~%")
       (format nil "step 4 : labeling ~%")
       (format nil "step 5 : making sammon map~%")
       (format nil "384 entries in codebook~%")
       (format nil "xma-xmi 3.0798202668990733 yma-ymi 2.1309072126802384~%"))
     (do-som-by-filename (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/som/animal.dat") "hexa" "gaussian"
                         24 16 123 10000 5 2400 10
       '(:absolute #+unix "tmp" #+mswindows "temp")))
  #+ (or sbcl ccl allegro)
  (assert-true (string= (concatenate 'string
                           (format nil "~%in-data-file [~s]~%" (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/som/animal.dat"))
                           (format nil "s-topol[hexa] s-neigh[gaussian] xdim[24] ydim[16] nrand[123]~%")
                           (format nil "num-label[10]~%")
                           (format nil "step 1 : initialization ~%")
                           (format nil "step 2 : learning ~%")
                           (format nil "step 3 : calibration ~%")
                           (format nil "step 4 : labeling ~%")
                           (format nil "step 5 : making sammon map~%")
                           (format nil "384 entries in codebook~%")
                           (format nil "xma-xmi 3.0798202668990733 yma-ymi 2.1309072126802384~%"))

                        (with-output-to-string (*standard-output*)  (do-som-by-filename (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/som/animal.dat") "hexa" "gaussian"
                                                   24 16 123 10000 5 2400 10
                                                   '(:absolute #+unix "tmp" #+mswindows "temp")))))

  (multiple-value-bind (out-pathname ps-pathname)
        (do-som-by-filename (clml.utility.data:fetch "https://mmaul.github.io/clml.data/sample/som/animal.dat") "hexa" "gaussian"
                            24 16 123 10000 5 2400 10
                            '(:absolute #+unix "tmp" #+mswindows "temp"))
      (assert-true (probe-file out-pathname))
      (assert-true (probe-file ps-pathname))
      (with-open-file (stream out-pathname)
        (assert-eql (read stream) 3)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce  0.0 'single-float)
                    #+ allegro 0.0d0)
        (assert-eql (read stream) #- allegro (coerce 15.0 'single-float)
                    #+ allegro 15.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce 0.0 'single-float)
                    #+ allegro 0.0d0)
        (assert-eql (read stream) #- allegro (coerce 0.0 'single-float)
                    #+ allegro 0.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce  23.0 'single-float)
                    #+ allegro 23.0d0)
        (assert-eql (read stream) #- allegro (coerce 1.0 'single-float)
                    #+ allegro 1.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce  21.0 'single-float)
                    #+ allegro 21.0d0)
        (assert-eql (read stream) #- allegro (coerce  0.0 'single-float)
                    #+ allegro 0.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce 9.0 'single-float)
                    #+ allegro 9.0d0)
        (assert-eql (read stream) #- allegro (coerce 15.0 'single-float)
                    #+ allegro 15.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce 0.0 'single-float)
                    #+ allegro 0.0d0)
        (assert-eql (read stream) #- allegro (coerce 10.0 'single-float)
                    #+ allegro 10.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce 23.0 'single-float)
                    #+ allegro 23.0d0)
        (assert-eql (read stream) #- allegro (coerce 15.0 'single-float)
                    #+ allegro 15.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce 17.0 'single-float)
                    #+ allegro 17.0d0)
        (assert-eql (read stream) #- allegro (coerce 15.0 'single-float)
                    #+ allegro 15.0d0)
        (read-line stream)
        (assert-eql (read stream) #- allegro (coerce 12.0 'single-float)
                    #+ allegro 12.0d0)
        (assert-eql (read stream) #- allegro (coerce 0.0 'single-float)
                    #+ allegro 0.0d0))))
